name: shorty
description: "contents for social media using AI"
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.1.1
  google_sign_in: ^6.0.2
  cached_network_image: ^3.1.0+1
  logger: any
  json_annotation: ^4.4.0
  shared_preferences: ^2.0.12
  synchronized:
  pretty_dio_logger: ^1.2.0-beta-1
  retrofit: ^4.0.1
  google_fonts: ^6.1.0
  # flutter_facebook_auth: ^6.0.3
  auto_size_text: ^3.0.0
  flutter_screenutil: ^5.1.0
  intl: ^0.19.0
  date_picker_timeline: ^1.2.3
  flutter_dotenv: ^5.0.2
  # share: ^2.0.4
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  firebase_messaging: ^15.0.3
  flutter_bloc: ^8.0.1
  bloc: ^8.0.2
  equatable: ^2.0.3
  permission_handler: ^11.0.1
  geocoding: ^3.0.0
  location: ^7.0.0
  day_night_time_picker: ^1.0.5
  freezed_annotation: ^2.0.3
  shimmer: ^3.0.0
  connectivity_plus: ^6.0.3
  url_launcher: ^6.3.0
  firebase_crashlytics: ^4.0.3
  firebase_analytics: ^11.2.0
  firebase_performance: ^0.10.0+3
  firebase_performance_dio: ^0.7.1
  flutter_local_notifications: ^17.2.1+2
  firebase_remote_config: ^5.0.3
  flutter_svg: ^2.0.10+1
  # flutter_web_auth_2: ^4.0.1
  oauth2_client: ^3.3.0
  crypto: ^3.0.5
  in_app_purchase: ^3.0.1
  in_app_purchase_platform_interface: ^1.4.0
  cloud_firestore: ^5.4.4
  webview_flutter: ^4.10.0
  network_monitor_cp: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  analyzer: any
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^9.1.2
  source_gen: ^1.2.6
  freezed: ^2.4.6
  

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/jsons/
